### ISSUE TITLE
Include peer-dependencies in package.json

### ISSUE THREAD

**Issue by pulasthibandara** [hally9k/redux-graphql-subscriptions#1]
Including peer-dependencies for `Redux`, `Redux-thunks` and `subscriptions-transport-ws` will help the setup of the package.
https://nodejs.org/en/blog/npm/peer-dependencies/

**Comment by hally9k** [comment]
It doesn't prescribe the usage of thunks but a side-effect lib is required for sure. `subscriptions-transport-ws` is a hard dependency. `redux` on the other hand should be a peerDep... I will add.

**Comment by hally9k** [comment]
@pulasthibandara I've added a peer dependency of redux `>= 3.7.0`...
