### ISSUE TITLE
Example app of how to use it

### ISSUE THREAD

**Issue by muaaz-vf** [hally9k/redux-graphql-subscriptions#2]

**Comment by waleedarshad-vf** [comment]
+1

**Comment by hally9k** [comment]
@muaaz-vf @waleedarshad-vf Does the getting started not explain well enough? Are you requesting a code example you can run in the repo?

**Comment by muaaz-vf** [comment]
I am a newbie so don't know how it will work. this library is abstraction of "subscriptions-transport-ws" so unable to understand under lying domain. if you make it. It will be equally help for both newbie and experts.

A big picture is worth a thousand words

Thanks

**Comment by muaaz-vf** [comment]
Any working example which can help us using this library would be great.

**Comment by hally9k** [comment]
@waleedarshad-vf @muaaz-vf
I know it's been a little while but I'm updating and using this middleware again now so I added a working example.
Readying it for a 1.0 release so your feedback on api, readme etc would be awesome.
Just tests to be written and I'll start thinking about releasing.
